# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='group',
            new_name='groups',
        ),
    ]
