# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20160918_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
