# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20160918_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='fields',
        ),
        migrations.AddField(
            model_name='emailfields',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mail.Email'),
            preserve_default=False,
        ),
    ]
