# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20160920_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfields',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
