# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20160920_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailfields',
            unique_together=set([('email', 'name')]),
        ),
    ]
