# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20160920_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='recieved_emails',
            field=models.ManyToManyField(related_name='sent_to', through='mail.Log', to='mail.Email'),
        ),
    ]
